sudo : required
services:
  - docker

before_install:
  - docker build  -t shaharboro/docker-react -f Dockerfile-dev .

script:
  - docker run -e CI=true shaharboro/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "dicker0react"
  env: "Dicker0react-env"
  bucket_name: "elasticbeanstalk-us-west-2-414935755761"
  bucket_path: ".elasticbeanstalk"
  on:
    branch: master
  access_key_id: "14141434"
  secret_access_key:
    secure: "ffffefwer34555"